### ISSUE TITLE
[Feature request] Shazam links

### ISSUE THREAD

**Issue by DaedalusBLN** [Ty3uK/songlink-android#1]
Hi,

I stumbled upon your awesome app and wrote about it on reddit today, because it is awesome.

Quick question: would it be possible to add support for Shazam links? Sadly even the Google Play Music links Shazam provides seem to be search queries on platforms, not actual links. What I am asking is probably a server-side issue, but maybe song.link's API provides a solution already?

Here's a Shazam share link: https://www.shazam.com/track/509900735/close-to-me

Here's the Google Play Music link for the same track as provided by Shazam: https://play.google.com/music/search/Close+to+Me+Sunny+Lax

Can't seem to get Shazam's URL for Apple Music as clicking that button gives no choice, it just fires up the GPlay page for the Apple Music app.

Thanks for all your efforts so far, this tool is a lifesaver!

**Comment by AlexWayfer** [comment]
As I know, Odesli itself doesn't support Shazam links. So, you need to write to their support, not here.

**Comment by Ty3uK** [comment]
> As I know, Odesli itself doesn't support Shazam links. So, you need to write to their support, not here.

That's correct 🤝
